### ISSUE TITLE
TypeError: summary() got an unexpected keyword argument 'alpha'

### ISSUE THREAD

**Issue by ThomasHoppe** [treszkai/best#6]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [18], in <module>
----> 1 best_out.summary()

File ~/.local/lib/python3.8/site-packages/best/model.py:278, in BestResults.summary(self, credible_mass)
    267 """Return summary statistics of the results
    268 
    269 Parameters
   (...)
    275     Default: 0.95.
    276 """
    277 check_credible_mass(credible_mass)
--> 278 return pm.summary(self.trace, alpha=(1 - credible_mass))

TypeError: summary() got an unexpected keyword argument 'alpha'

I am running:
python 3.8.10
pymc3 3.11.4

**Comment by ThomasHoppe** [comment]
A workaroud is:

import pymc3 as pm
pm.summary(best_out.trace)

**Comment by treszkai** [comment]
Hi @ThomasHoppe, thanks for the issue report and the provided workaround. The error will be fixed in 168 hours.

**Comment by treszkai** [comment]
Fixed in version 2.0.5.
